// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaPlaylistEntry = { id: string, url: string, title: string, playlist_index: number | null, };
