// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetadataResponse = { url: string, filename: string, size: string, size_bytes: number, };
