// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtensionDownload = { urls: Array<string>, referer: string | null, silent: boolean, filename: string | null, };
